DROP TABLE IF EXISTS REGISTRATIONS;
DROP TABLE IF EXISTS EVENTS;
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
    id	INT NOT NULL,
    name	VARCHAR(512),
    email	VARCHAR(512) NOT NULL UNIQUE,
    password	VARCHAR(512),
    PRIMARY KEY (id)
);

INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('0', 'Mary Jackson', 'maryj@abc.com', 'maryj');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('1', 'Karen Addams', 'karena@abc.com', 'karena');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('2', 'Scott Ramsey', 'scottr@abc.com', 'scottr');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('3', 'Leena Balas', 'lbalas0@domainmarket.com', 'sV3}x+W(6#E3h5~/');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('4', 'Sigvard Wein', 'swein1@google.com.au', 'bA3(l%|,VMb)');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('5', 'Denver Robelow', 'drobelow2@amazon.com', 'gW4@TvoP3');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('6', 'Sal Klesl', 'sklesl3@soup.io', 'nQ5`6S|Z5&aA<D%c');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('7', 'Dodi Mourbey', 'dmourbey4@devhub.com', 'yS7(qiW{?po@');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('8', 'Shay Bassil', 'sbassil5@yahoo.com', 'yK5*+2gB*Gjh');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('9', 'Stefan Emblem', 'semblem6@who.int', 'uZ9"(&NbN');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('10', 'Lela Mackrell', 'lmackrell7@java.com', 'yL4/~niK/>0f');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('11', 'Chas Lardner', 'clardner8@un.org', 'eZ6<3X.t');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('12', 'Giraud Allner', 'gallner9@blogs.com', 'xM3(qw6V,');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('13', 'Brietta Brasseur', 'bbrasseura@ed.gov', 'vP7/t>6/f');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('14', 'Ivory Colafate', 'icolafateb@taobao.com', 'eM4{>#(i');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('15', 'Gherardo Meiklam', 'gmeiklamc@mac.com', 'vY4<+x0gx|b');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('16', 'Hortensia Drury', 'hdruryd@cnbc.com', 'wG0}GsCf*|9LC');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('17', 'Rana Martina', 'rmartinae@amazon.co.uk', 'kI1%7B}%Yi(ZIh1');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('18', 'Nixie Obey', 'nobeyf@myspace.com', 'wW8*Ir*0+');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('19', 'Stephana Bilverstone', 'sbilverstoneg@hugedomains.com', 'dX6?}E@Y_');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('20', 'Emanuele Osinin', 'eosininh@yelp.com', 'lN6>sE2)6xeS0');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('21', 'Koressa Nattrass', 'knattrassi@google.nl', 'pW9=1bEMI');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('22', 'Xylia Duke', 'xdukej@delicious.com', 'vO5.Zwti7');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('23', 'Tommy Evemy', 'tevemyk@unc.edu', 'nR0=5JJ>IJg8?7<q');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('24', 'Trudi Barnfield', 'tbarnfieldl@technorati.com', 'cN9@obA_(PKQ');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('25', 'Teriann Skittrell', 'tskittrellm@bizjournals.com', 'pI8#jNgd77{bu');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('26', 'Devina Bariball', 'dbariballn@intel.com', 'bF5%klic8');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('27', 'Joly Ropkes', 'jropkeso@ocn.ne.jp', 'fQ3*@~/U=54R');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('28', 'Skip Kettles', 'skettlesp@vk.com', 'aN7&W1gKx$=');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('29', 'Mariejeanne Milkeham', 'mmilkehamq@ustream.tv', 'eP2>earf');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('30', 'Kirstin Meeson', 'kmeesonr@shinystat.com', 'vB3}0>%C6');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('31', 'Carmine Dominicacci', 'cdominicaccis@paginegialle.it', 'nY8/bW>7fl');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('32', 'Darin Vairow', 'dvairowt@rediff.com', 'bB8`D+|}a~H_>b7v');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('33', 'Sydelle Mussared', 'smussaredu@ustream.tv', 'aY9@yhNc/H/lr');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('34', 'Ebenezer Jocic', 'ejocicv@studiopress.com', 'iJ5#O2oHFUT');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('35', 'Audrey Ramshay', 'aramshayw@liveinternet.ru', 'jX9)hheaeO!o');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('36', 'Oneida Heathcott', 'oheathcottx@networksolutions.com', 'vX1=@owi&E_9');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('37', 'Rebeka Losebie', 'rlosebiey@soup.io', 'dK3_T=q5l&H_t');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('38', 'Derk Marshal', 'dmarshalz@indiegogo.com', 'oX0dcY|73@');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('39', 'Mollee Gaitskill', 'mgaitskill10@twitter.com', 'jC6=m4KL@');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('40', 'Maddalena Phetteplace', 'mphetteplace11@ask.com', 'bL3~_}M@E6');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('41', 'Harriet Duckhouse', 'hduckhouse12@ucla.edu', 'uX2<iFU`n');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('42', 'Ezra Atcheson', 'eatcheson13@blogtalkradio.com', 'oS5{tm$TO+sP>Q');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('43', 'Krissie Bessey', 'kbessey14@walmart.com', 'cU9.4>m*(n)}E"');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('44', 'Keene Moran', 'kmoran15@geocities.jp', 'yF2_6M<X');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('45', 'Ric Espinho', 'respinho16@dion.ne.jp', 'aA0{ZnFU');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('46', 'Ainslie Wardlow', 'awardlow17@vk.com', 'nH7}gZvq');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('47', 'Eugene Darleston', 'edarleston18@oakley.com', 'pI1}SR|1WejR');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('48', 'Johnath Wyett', 'jwyett19@apple.com', 'uS4,dg{+l5S');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('49', 'Freemon Hutchason', 'fhutchason1a@theglobeandmail.com', 'uH7OS)EEcle8Bq');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('50', 'Amaleta Padmore', 'apadmore1b@weibo.com', 'gW3)BxXy');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('51', 'Yvette Gurnee', 'ygurnee1c@squidoo.com', 'yF1"E(|l');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('52', 'Tiertza Dorward', 'tdorward1d@wufoo.com', 'uN0/H_e#,');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('53', 'Lauraine Desborough', 'ldesborough1e@slideshare.net', 'xN7"E|PN+$');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('54', 'Quentin McGenn', 'qmcgenn1f@sun.com', 'cD8~rJs0,Y');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('55', 'Babb Burnell', 'bburnell1g@chicagotribune.com', 'vY2_=5}2xd7P}K');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('56', 'Beret Whybrow', 'bwhybrow1h@tripadvisor.com', 'qU1*GAERzV');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('57', 'Dorree Faughey', 'dfaughey1i@independent.co.uk', 'rJ8"6Iny');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('58', 'Gusti Ratcliff', 'gratcliff1j@usnews.com', 'bJ7D@s{');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('59', $$Lyn O'Cullen$$, 'locullen1k@census.gov', 'mJ3?_G1{T~>');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('60', 'Cassey Consterdine', 'cconsterdine1l@odnoklassniki.ru', 'pT1*leoyU}6O');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('61', 'Denny Golborn', 'dgolborn1m@studiopress.com', 'rA9!b7+ZMZ>%d');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('62', 'Ruy MacManus', 'rmacmanus1n@tamu.edu', 'gL3>RlqW%');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('63', 'Maurine Coles', 'mcoles1o@bbc.co.uk', 'pC2/j6Fy`9eaP');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('64', $$Laural O' Borne$$, 'lo1p@forbes.com', 'uY5?NkhnXM(>>b');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('65', 'Gordon Wrightem', 'gwrightem1q@tinypic.com', 'qJ9&Lx9q5');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('66', 'Leeland Kellog', 'lkellog1r@indiatimes.com', 'pE6$TArk');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('67', 'Ruthy Coggell', 'rcoggell1s@ca.gov', 'tD2.k+QD');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('68', 'Zach Simnor', 'zsimnor1t@unc.edu', 'jV2~1o+b');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('69', 'Romain Albasiny', 'ralbasiny1u@tinyurl.com', 'wG4&"s>AgQajJt');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('70', 'Ursala Limpricht', 'ulimpricht1v@acquirethisname.com', 'rP8`m*._72E%y6');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('71', 'Viv Lomasney', 'vlomasney1w@merriam-webster.com', 'oS7|rr@En$7x');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('72', 'Helaina Larvor', 'hlarvor1x@dyndns.org', 'rA2{e}~`ReB');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('73', 'Nada Leacock', 'nleacock1y@aboutads.info', 'zT3}>4DnQ3Pmh/4m');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('74', $$Garrott O' Dornan$$, 'go1z@t.co', 'yB8U*G*3&O$X');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('75', 'Cris Kiddell', 'ckiddell20@thetimes.co.uk', 'zC3"QOnQP');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('76', 'Ase Branney', 'abranney21@freewebs.com', 'xN5,qgxy6WFap');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('77', 'Rebekah Van Der Walt', 'rvan22@msn.com', 'test');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('78', 'Rudiger Castellani', 'rcastellani23@issuu.com', 'zY2"RutQZBk$?"<K');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('79', 'Shanta Rubery', 'srubery24@amazonaws.com', 'cR8>R@#fp7');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('80', 'Karlens Landal', 'klandal25@hhs.gov', 'jZ7"nvrkBxzN');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('81', 'Teodoro Kerner', 'tkerner26@etsy.com', 'wR6?2WL8rX');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('82', 'Gail Plumbley', 'gplumbley27@hostgator.com', 'yC0`Gv*X{B<U3t8');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('83', 'Genna Biggerdike', 'gbiggerdike28@comsenz.com', 'uK0?R1KnbL');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('84', 'Barbey Gaspard', 'bgaspard29@umn.edu', 'xE25R~u%T@');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('85', 'Felicio Haet', 'fhaet2a@homestead.com', 'xV6{zvA/y2xvRIqt');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('86', 'Tymon Gounard', 'tgounard2b@live.com', 'hT5*YAks9/A~CkE');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('87', 'Aluin Botright', 'abotright2c@bandcamp.com', 'bI5!A+$ZQiKMDEK');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('88', 'Sile Gerriet', 'sgerriet2d@msn.com', 'wY9+WR1q');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('89', 'Collette Smickle', 'csmickle2e@blinklist.com', 'iD4.sXv6z{3zE"=7');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('90', 'Harriot Vaughten', 'hvaughten2f@blogtalkradio.com', 'bX2&bK!+pT');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('91', 'Cecil Tomasek', 'ctomasek2g@si.edu', 'mL8&TTvTPYV"T`cQ');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('92', 'Byran Showler', 'bshowler2h@toplist.cz', 'jX9!"5Y~f');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('93', 'Aluino Churches', 'achurches2i@digg.com', 'gL1,H|b0w,q');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('94', 'Emalee Pascho', 'epascho2j@lycos.com', 'zL9{$y(tn');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('95', 'Hamish Brack', 'hbrack2k@posterous.com', 'oS6+ZF!CA1');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('96', 'Vivianne Sanderson', 'vsanderson2l@unc.edu', 'zP6}SO+)mM3LA5g');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('97', 'Kara Bagguley', 'kbagguley2m@csmonitor.com', 'bD7#|CYx');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('98', 'Cherilynn Backsal', 'cbacksal2n@de.vu', 'bA1_~(TA');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('99', 'Tabbitha Haggarth', 'thaggarth2o@usda.gov', 'nG6&06DPw');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('100', 'Thia Cromer', 'tcromer2p@sitemeter.com', 'qK1K@w9y');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('101', 'Jesus Ianiello', 'jianiello2q@microsoft.com', 'gB3<uJ1w');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('102', 'Stan Mulcock', 'smulcock2r@uiuc.edu', 'oX0<Dj)');
INSERT INTO CUSTOMERS (id, name, email, password) VALUES ('103', 'admin', 'admin@test.com', 'admin');