services:
  data-service:
    build: ./data-service
    ports:
      - "8080:8080"
    networks:
      - api
    environment:
      - DATA_SERVICE_URL: "http://data-service:8080"
  authentication-service:
    build: ./authentication-service
    ports:
      - "8081:8081"
    networks:
      - api
  frontend:
    build: ./frontend-react-app/react
    ports:
      - "5173:5173"
    networks:
      - api

networks:
  api:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "localhost"
